nginx-ingress:
  controller:
    image:
      repository: gcr.io/jenkinsxio/nginx-ingress-controller
    replicaCount: 3
    extraArgs:
      publish-service: kube-system/jxing-nginx-ingress-controller
    service:
      targetPorts: 
        https: http
      omitClusterIP: true
{{- if eq .Requirements.cluster.provider "eks" }}
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:eu-west-1:242867168342:certificate/549faf22-0bc6-45ee-a075-b193eda45555
        service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
        #service.beta.kubernetes.io/aws-load-balancer-type: nlb
{{- end }}
  defaultBackend:
    service:
      omitClusterIP: true
  rbac:
    create: true
