external-dns:
  enabled: {{ .Requirements.ingress.externalDNS }}
  image:
    tag: 0.5.16-debian-9-r8
  sources:
  - ingress
  - service
{{- if eq .Requirements.cluster.provider "eks"}}
  provider: aws
  aws:
    region: {{ .Requirements.cluster.region}}
  securityContext:
    fsGroup: 65534
{{- else if eq .Requirements.cluster.provider "gke"}}
  provider: google
  google:
    serviceAccountSecret: external-dns-gcp-sa
 {{- if hasKey .Requirements.cluster "project" }}
    project: "{{ .Requirements.cluster.project }}"
 {{ end }}
{{- else if eq .Requirements.cluster.provider "aks"}}
  provider: azure
  azure:
    secretName: azure-external-dns-secret
{{- end}}

  rbac:
    create: true
    serviceAccountName: external-dns
    serviceAccountAnnotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::242867168342:role/k8s-external-dns
  domainFilters:
{{- range .Requirements.environments }}
 {{- if .ingress.domain }}
  - "{{ .ingress.domain }}"
  {{- end }}
{{- end }}
